### ISSUE TITLE
cuda runtime versionに関するエラー

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.meister#17]
#10 の子
>  CUDA driver version is insufficient for CUDA runtime version 

`sudo apt update;sudo apt upgrade;sudo apt install cuda` で直せる模様、試す
>Installs all CUDA Toolkit and Driver packages. Handles upgrading to the next version of the cuda package when it's released.
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html

**Comment by sakakendo0321** [comment]
https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#ubuntu-installation

**Comment by sakakendo0321** [comment]
```
$ python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy
>>> a=cupy.arrange(9).reshape(3,3).astype('f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cupy' has no attribute 'arrange'
>>> a=cupy.arange(9).reshape(3,3).astype('f')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/cupy/creation/ranges.py", line 55, in arange
    ret = cupy.empty((size,), dtype=dtype)
  File "/usr/local/lib/python3.5/dist-packages/cupy/creation/basic.py", line 20, in empty
    return cupy.ndarray(shape, dtype, order=order)
  File "cupy/core/core.pyx", line 150, in cupy.core.core.ndarray.__init__
  File "cupy/cuda/memory.pyx", line 517, in cupy.cuda.memory.alloc
  File "cupy/cuda/memory.pyx", line 1064, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/memory.pyx", line 1084, in cupy.cuda.memory.MemoryPool.malloc
  File "cupy/cuda/device.pyx", line 19, in cupy.cuda.device.get_device_id
  File "cupy/cuda/runtime.pyx", line 165, in cupy.cuda.runtime.getDevice
  File "cupy/cuda/runtime.pyx", line 137, in cupy.cuda.runtime.check_status
cupy.cuda.runtime.CUDARuntimeError: cudaErrorInsufficientDriver: CUDA driver version is insufficient for CUDA runtime version
```

**Comment by sakakendo0321** [comment]
cupy 動作確認できた
```
(2018.meister) nvidia@tegra-ubuntu:~/workspace/2018.meister$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cupy as cp
>>> x=cp.array([1,2,3,4,5])
>>> x
array([1, 2, 3, 4, 5])```
