### ISSUE TITLE
jetsonからservoをまわす

### ISSUE THREAD

**Issue by sakakendo** [teamET/2018.meister#21]
`sudo apt install python-smbus`

**Comment by sakakendo0321** [comment]
https://github.com/cberner/lynxmotion

**Comment by Spacekoki** [comment]
>`bash`
sudo pip install pyssc32
The directory '/home/nvidia/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/nvidia/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyssc32
  Downloading https://files.pythonhosted.org/packages/5d/91/93e79420111290f76833b3df25477d46bebf96fd0ebbe1383b3857893f57/pyssc32-0.4.2.tar.gz
    Complete output from command python setup.py egg_info:
    Warning: For Servo Script PyYAML molule requiredTraceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wd3j5sl5/pyssc32/setup.py", line 17, in <module>
        long_description=desc(),
      File "/tmp/pip-install-wd3j5sl5/pyssc32/setup.py", line 12, in desc
        + open(join(dirname(__file__), 'ChangeLog.rst')).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-wd3j5sl5/pyssc32/ChangeLog.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-wd3j5sl5/pyssc32/

**Comment by sakakendo0321** [comment]
もしかしたらpython 2ならいけるってやつなのかもしれない
[](url)
![img_20190213_164536](https://user-images.githubusercontent.com/23027593/52696034-4ed7e780-2fb1-11e9-88ca-526c05a45fbd.jpg)

**Comment by sakakendo0321** [comment]
```
(2018.meister) nvidia@tegra-ubuntu:~/workspace/2018.meister$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssc32
>>>```

**Comment by Spacekoki** [comment]
pip2 install pyserialもしなきゃね
