### ISSUE TITLE
zedからdarknetに渡したときのエラー

### ISSUE THREAD

**Issue by sakakendo0321** [teamET/2018.meister#38]
```
Traceback (most recent call last):
  File "main.py", line 83, in <module>
    get_available()
  File "main.py", line 66, in get_available
    results = net.detect(Image(np.asarray(image.get_data())))
  File "pydarknet.pyx", line 30, in pydarknet.Image.__cinit__
AssertionError: ASSERT::3channel RGB only!!
```
sl::Matはrgbaで管理しているが、cv::Matはrgb管理しているみたい

**Comment by sakakendo0321** [comment]
```
np.delete(image.get_data(),3,2)
```
